### ISSUE TITLE
[Feature Request] Push token edits to prototype

### ISSUE THREAD

**Issue by LukasPrism** [Aedif/multi-token-edit#1]
I'm not just putting this here to be first, promise!

It would be great if your module gave an option to push token edits back to the prototypes. This would be quite powerful, eg. if you're making edits to all player tokens but don't want to lose those edits if you replace the tokens from the sidebar.

Not sure if the best solution would be an additional checkbox ("☑︎ Also update Prototype Tokens")... or maybe an additional button so you either "Apply Changes" or "Apply and Update Prototypes". What do you think?

Aside from custom-made macros, this would be the quickest way to update several prototypes at once. Even dragging a folder of tokens to the map and using your module would be a speedy way to do mass prototype edits.

Someone else also brought this up on discord so that gave me the push to put it up here. Thanks again for a wonderful addition to Foundry :)

**Comment by Aedif** [comment]
Yup something like that should be doable. Might add a confirmation dialog or some other safety feature to prevent accidentally updating the prototypes by accident.

**Comment by Aedif** [comment]
New button present in release [1.4.0](https://github.com/Aedif/multi-token-edit/releases/tag/1.4.0) 👍

**Comment by LukasPrism** [comment]
Don't think I didn't notice the bold **Token** in the package release. Thanks heaps!
