### ISSUE TITLE
Warning in v10

### ISSUE THREAD

**Issue by Nysterian** [Aedif/multi-token-edit#10]
I haven't noticed any problems with the module, but this warning appears whenever I load the module in v10:

`[multi-token-edit] The module "multi-token-edit" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object`

Thought I'd at least mention it to call attention to it.

**Comment by Aedif** [comment]
Thanks for the shout. At the moment the module supports both v9 and v10 under the same release and have to share the same manifest. v10 manifest is not compatible with v9 so until I drop support for v9 the warning will unfortunately have to remain.

**Comment by Aedif** [comment]
Btw is this a notification or just a console warning?

**Comment by Nysterian** [comment]
It is kind of both, the message from before only appears in the console, but whenever foundry is opened, I get the following notification:
`1 compatibility warning detected with installed Packages. Consult your console log (F12) for details.`

The number used to be bigger, but all the other modules that brought that number up have updated by now.

**Comment by Aedif** [comment]
Should be fixed in the latest release
