### ISSUE TITLE
Compatibility to Health Estimate

### ISSUE THREAD

**Issue by vt-tom** [Aedif/multi-token-edit#11]
It would be nice if Mass Edit could be compatible to Health Estimate. Now, it shots the Tab twice in the Token Mass Edit Window. Also it shows the configuration possibilities three times in a row.

![grafik](https://user-images.githubusercontent.com/80099175/210200663-bd4ae09e-b73d-46f2-9378-13db9a9d692f.png)

**Comment by Aedif** [comment]
I needed to use a `hack` to make SmallTime work with Mass Edit which appears to have caused issues for this particular module... I created a pull request for SmallTime to address the underlying problem. 

Until it is accepted I wont be able to make Mass Edit work for both Small Time and Health Estimate:

https://github.com/unsoluble/smalltime/pull/167

**Comment by Aedif** [comment]
Should be fixed in release [1.29.1](https://github.com/Aedif/multi-token-edit/releases/tag/1.29.1)

**Comment by vt-tom** [comment]
Works, thank you very much
