### ISSUE TITLE
Doesn't work with Bar Brawl

### ISSUE THREAD

**Issue by Exocist** [Aedif/multi-token-edit#13]
When trying to edit the prototype tokens of bar brawl using this + multiple document selection, clicking load defaults, right clicking resource and then clicking apply updates to proto token, the tokens are not updated.

**Comment by Aedif** [comment]
Did some investigation.

It seems that Bar Brawl simply relies too much on always receiving ALL the data that you see on the form which makes it incompatible with Mass Edit which only submits selected data.

I attempted a workaround which functioned to a limited degree... It made updates possible but caused other kinds of problems which would be hard for users to understand and remedy. 

In the end I decided that it was simply not worth it to add supprt. 

Sorry about this.
