### ISSUE TITLE
Feature request: Allow multiple color pickers for random color application via DD Tint

### ISSUE THREAD

**Issue by PlasticMohawk** [Aedif/multi-token-edit#14]
Use Case:
As a Foundry GM-level user, I'm making an encounter map. I'm adding a cluster of bush assets to the map. These assets are red so they may be colored via the Dungeondraft Tint macro/functionality. I want all of these bushes to be a slightly different shade of green.

Ideal behavior:
I select all of the red bush tiles I just placed, and open Mass Edit. In the Dungeondraft Tint section, I have up to (for example) five color pickers with which I can build my palette. I select my five different shades of green and edit the tiles. This will apply a different shade of green randomly to each bush tile.

I could also use this technique to create vibrant flower or mushroom beds, differently-colored items on a merchant's bench, etc.

Current behavior:
There is only one color picker, so selecting a mass of tiles and applying this sort of edit will color everything the same color. In order to color everything individually, I would need to select everything individually and color them one at a time, in which case it's almost easier to use the Dungeondraft Tint macro directly.

**Comment by Aedif** [comment]
Randomization at the moment is a patreon exclusive feature:

https://user-images.githubusercontent.com/7693704/219413150-a8eb55a2-f36e-4bfd-b8a1-a9bcbb6b8ca4.mp4

It encompasses color, drop-downds, images, numbers, coordinates, and text.
