### ISSUE TITLE
Update Prototypes not working for me

### ISSUE THREAD

**Issue by davelacorneille** [Aedif/multi-token-edit#2]
Hi and thank you for this module! :) Very useful.

I don't know if I'm doing something wrong but I'm not able to update the linked prototype of the selected token.

Thank you!

**Comment by Aedif** [comment]
Thanks for the shout, I accidentaly broke this functionality in release 1.7.0

Should be fixed as of [1.7.1](https://github.com/Aedif/multi-token-edit/releases/tag/1.7.1)
