### ISSUE TITLE
Critical World-Loading Bug in Foundry v11.300

### ISSUE THREAD

**Issue by Dumbhuman** [Aedif/multi-token-edit#20]
I just updated to Foundry v11.300.  I installed and enabled the Mass Edit module (among 5 others) in a test world.  After using the prompt to reload the Foundry App, almost all UI elements disappeared (as in screenshot below).

![image](https://github.com/Aedif/multi-token-edit/assets/63615591/ed6cbb9d-4519-43d8-a11f-60af74a78672)

I closed Foundry and relaunched it, but received errors related to Mass Edit when I tried to launch that world.  I closed Foundry again, made a new test world and this time enabled only Mass Edit from the installed modules.  The same blank Foundry screen appeared after reloading.  Neither of the two worlds tested will launch and the console shows the errors below from clicking to try to launch one world followed by the other.

![image](https://github.com/Aedif/multi-token-edit/assets/63615591/d179ea55-4d29-4be6-bb79-99458222b6b8)

Hopefully there's something helpful for you in those error messages, because Mass Edit is one of the most helpful modules for me.  Please let me know if there's any other information you'd like from me.

**Comment by Aedif** [comment]
What version of the module are you on? This should have been fixed in release 1.43.3

**Comment by Dumbhuman** [comment]
> What version of the module are you on? This should have been fixed in release 1.43.3

Well, the good news is that I just updated to 1.43.3 and can confirm that fixed the issue!

The bad news, or at least weird news, is that I only installed Mass Edit today, so I don't know why it installed 1.43.2 if 1.43.3 was released 3 days ago.

**Comment by Aedif** [comment]
Ah I forgot to update it on Foundry DB. Was waiting for another user to confirm the fix. Fresh installs should now immediately pick up 1.44.3

**Comment by Dumbhuman** [comment]
Well, I'm glad it's all good now!  Many thanks for the wonderful module!
