### ISSUE TITLE
DungeonDraft (TMFX) option throwing console error when attempting to recolor a tile

### ISSUE THREAD

**Issue by PlasticMohawk** [Aedif/multi-token-edit#21]
Foundry v10, PF2E

I have a tile I wish to recolor using the DungeonDraft (TMFX) filter. I'm using the options in the below screenshot.

When clicking "Apply Changes", rather than recoloring, I get the following console error:

```
tokenmagic.js:446 Uncaught (in promise) 
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'getFlag')
[Detected 2 packages: tokenmagic, multi-token-edit]
    at Object.addUpdateFilters (tokenmagic.js:446:34)
    at applyDDTint (tmfx.js:6:22)
    at checkApplySpecialFields (forms.js:1209:15)
    at MassConfig.performMassUpdate (forms.js:1128:9)
    at MassConfig.massUpdateObject (forms.js:643:27)
    at MassConfig._updateObject (forms.js:621:19)
    at MassConfig._onSubmit (foundry.js:5916:18)
```

I tested using the TMFX `39 - DungeonDraft Tint` macro directly on the tile, and this recolors the tile as expected.

Let me know if you need any additional information. Thanks!

![image](https://github.com/Aedif/multi-token-edit/assets/5216225/82106104-9ed8-44c8-a1f9-ec8dc017e987)

**Comment by Aedif** [comment]
Should be fixed in 1.43.4: https://github.com/Aedif/multi-token-edit/releases/tag/1.43.4
