### ISSUE TITLE
Unable to close Mass Edit window when editing lights.

### ISSUE THREAD

**Issue by dukayn** [Aedif/multi-token-edit#22]
In Foundry v11.302, if I'm editing lights using Mass Edit, the window doesn't close after hitting Apply Updates, not can it be closed via the Close button.

The only way to remove the Mass Edit window is via a page refresh.

**Comment by Aedif** [comment]
Should be fixed in https://github.com/Aedif/multi-token-edit/releases/tag/1.43.7

**Comment by dukayn** [comment]
Confirmed fixed. Thanks!

**Comment by dukayn** [comment]
Confirmed as fixed, thanks! :)
