### ISSUE TITLE
Can't edit Scene Presets

### ISSUE THREAD

**Issue by ctbritt** [Aedif/multi-token-edit#28]
getting this error: 
![CleanShot 2023-12-14 at 21 52 14@2x](https://github.com/Aedif/multi-token-edit/assets/4516034/13294bda-35da-4357-acb9-18bf3e82ed93)

Modules active: 
![CleanShot 2023-12-14 at 21 55 55@2x](https://github.com/Aedif/multi-token-edit/assets/4516034/e2c074fc-2f9e-4f7c-9596-c6bb31309c96)

**Comment by Aedif** [comment]
https://github.com/Aedif/multi-token-edit/releases/tag/1.51.1
