### ISSUE TITLE
BW Mass Edit - Bug when switching storage compendium

### ISSUE THREAD

**Issue by AporieTM** [Aedif/multi-token-edit#30]
Ok, this one might also be on me, but it surely is a bug.

In an attempt to get the new BW Mass Edit release to show the related prefabs, etc. I switched the storage compendium to nuts & bolts (hoping it would then at least show the macros).

Well, after switching it I can't open BW Mass Edit anymore. No click on the ME button, from whichever category just doesn't work. And there seems to be no way to change it back in the normal configuration.

PS.: using PF2e system if that helps.

here is what the console says:
TypeError: An error occurred while rendering $6e4e38012e8d2014$export$7a966e8b4abecc03 568. Cannot read properties of undefined (reading '050kpPPfqOa9XeJ2')
[Detected 1 package: multi-token-edit]
    at $74329e11c6ef615c$export$9cea25aeb7365a59.packToTree (collection.js:111:31)
    at async $74329e11c6ef615c$export$9cea25aeb7365a59.getTree (collection.js:34:22)
    at async $6e4e38012e8d2014$export$7a966e8b4abecc03.getData (forms.js:121:17)
    at async $6e4e38012e8d2014$export$7a966e8b4abecc03._render (foundry.js:5812:18)
    at async $6e4e38012e8d2014$export$7a966e8b4abecc03._render (foundry.js:6532:5)

onError	@	foundry.js:753
:gift:call_wrapped	@	libWrapper-wrapper.js:507
:gift:Hooks.onError#lib-wrapper	@	listeners.js:138
:gift:Hooks.onError#0	@	libWrapper-wrapper.js:187
(anonymous)	@	foundry.js:5771
Promise.catch (async)		
render	@	foundry.js:5769
(anonymous)	@	multi-token-edit.mjs:211
dispatch	@	jquery.min.js:2
y.handle	@	jquery.min.js:2

**Comment by Aedif** [comment]
I believe I found the issue. I'll fix it up, and also add some fail-safes to default back to the original compendium if something goes wrong, so that we don't end up in a situation agian where you can't swap back manually.
