### ISSUE TITLE
Post-Spawn script shows error in console, does not execute

### ISSUE THREAD

**Issue by bloy** [Aedif/multi-token-edit#31]
Putting something (anything, including `console.log('Hello')` ) into the post-spawn script and spawning that object results in:

`Uncaught (in promise) ReferenceError: documents is not defined` on the console and the post-spawn script not actually executing

it appears to be this line towards the end of `spawnPreset`, 
![image](https://github.com/Aedif/multi-token-edit/assets/1473405/ddc76a6a-164f-43d1-ac5d-e122085d416e)

I think that is supposed to be `allDocuments.map...` but I'm not certain enough on how to build this module to try it myself.

**Comment by Aedif** [comment]
Should be fixed in [1.64.0](https://github.com/Aedif/multi-token-edit/releases/tag/1.64.0)
