### ISSUE TITLE
[Feature Request] Mirror Prefabs

### ISSUE THREAD

**Issue by Crowguard** [Aedif/multi-token-edit#33]
This might be too difficult or even impossible to do, but possibly add a hotkey or method to be able to place prefabs so that all attached elements are mirrored (object images and locations). 

![image](https://github.com/Aedif/multi-token-edit/assets/99844555/9ea93acb-89fb-41f3-92af-eb21c06676cd)

**Comment by Aedif** [comment]
That's a feature request that should be made under `Token Attacher` module. While I could feasibly add mirroring for basic Mass Edit presets, as far as I'm aware `Token Attacher` only supports token rotation and scaling.

**Comment by Crowguard** [comment]
I did add it there as well; I just wasn't sure of where exactly in this environment it fit best, so I thought I'd cover both bases.

https://github.com/KayelGee/token-attacher/issues/116

**Comment by Aedif** [comment]
While prefab mirroring is still not possible (ME has no control over TA processes), pure ME presets can now be mirrored as of [1.71.3](https://github.com/Aedif/multi-token-edit/releases/tag/1.71.3)
