### ISSUE TITLE
Module Incompatibility with Foundry VTT Version 12

### ISSUE THREAD

**Issue by Niclasp1501** [Aedif/multi-token-edit#34]
I have encountered an issue with the module, which does not function properly with the latest Foundry update. The module was working perfectly in previous versions but appears to be incompatible with the latest version.

**Comment by Aedif** [comment]
This is being worked on. Most of the compatibility fixes have already been made and will be released soon

**Comment by Aedif** [comment]
https://github.com/Aedif/multi-token-edit/releases/tag/1.69.0
