### ISSUE TITLE
SHIFT+E does not open Mass Edit when multiple lights are selected

### ISSUE THREAD

**Issue by franckflo** [Aedif/multi-token-edit#35]
Hi,

I use FVTT 11.315 and Mass Edit 1.69.2. I noticed that selecting several ambient lights and pressing SHIFT+E does not open the Mass Edit tool. It works for other placeable, just not for lights. I used Find the Culprit to isolate the problem, which persists with only BaileyWiki Mass Edit enabled.

**Comment by tjlanza** [comment]
I can confirm this bug. Pressing SHIFT+E creates a logged error:
![image](https://github.com/Aedif/multi-token-edit/assets/21128724/e883d66d-0865-447f-9e8d-b170686b5b37)

**Comment by Aedif** [comment]
https://github.com/Aedif/multi-token-edit/releases/tag/1.69.3
