### ISSUE TITLE
Syntax error in module.json

### ISSUE THREAD

**Issue by Haladesta** [Aedif/multi-token-edit#36]
When updating, I get the following error:
`Error: Module validation errors: documentTypes: is not a valid sub-types configuration: 'RegionBehaviour' is not a valid Document type`

**Comment by Aedif** [comment]
The module has been split into v11 and v12 versions. If you have a v11 version isntalled you may need to re-install to make sure you're on the correct release going forward

**Comment by Haladesta** [comment]
I see. That seems to have fixed it, thanks
