### ISSUE TITLE
[v10] Scale (Ratio) for Tokens doesn't work

### ISSUE THREAD

**Issue by vt-tom** [Aedif/multi-token-edit#4]
The Value Scale (Ratio) for Tokens isn't working in Mass Edit. Wether in changing multiple Tokens or use the copy function.

![grafik](https://user-images.githubusercontent.com/80099175/188394165-be1f324d-a00a-4392-859a-5b58c359646a.png)

**Comment by Aedif** [comment]
Hi, it seems that v10 foundry made some specific changes regarding token scaling and mirroring which I need to account for.  

I'm working on a fix however I believe I have found a foundry bug which needs to be fixed before I proceed: Scaling and mirroring can't be updated independently of each other...

e.g. 
``_token.document.update({ scale: 1})`` will revert mirroring
and
``_token.document.update({ mirrorX: false, mirrorY: false })`` will revert scaling

**Comment by vt-tom** [comment]
I saw your bug report on Discord. That's good to know. 👍

**Comment by Aedif** [comment]
Hi a full workaround should now be present in release [1.11.0](https://github.com/Aedif/multi-token-edit/releases/tag/1.11.0)
