### ISSUE TITLE
Spawning In Token with Modify Preset Request

### ISSUE THREAD

**Issue by Tinykneebreaker** [Aedif/multi-token-edit#40]
Upon creating a token i would use for Loot Chests, I insert into a Create Prefab drag. While editing the Tabs and Fields, in the Spawning Tab, I allow for a Modify Request to be Prompt upon creating prefabbed token. Selected the "flags.monks-active-tiles.actions" field for prompt, but upon saving, i find out I am not allowed to create said token again. I can drag the prefab setting onto the canvas, but no Prompt to create. I can double click the prefab and a notification pops up "Mass Edit: Spawning [Loot Chest] " but no avail. When i REMOVE the modify prompt for said field, i can generate token again.

**Comment by Aedif** [comment]
https://github.com/Aedif/multi-token-edit/releases/tag/1.74.0
