### ISSUE TITLE
Massedit & LinkTokenBehabior

### ISSUE THREAD

**Issue by virtualGete** [Aedif/multi-token-edit#44]
hi,

imagine a cart (tile) upon which i draw a region with link token behavior. this defines a cart an actor can get on. 
now the cart is moved by an actor (lets say a horse). if you link the horse to the rest the whole systems works until the horse colides with the region. because then he both is linked to the node and the region. 
Right clicking the link will solve the issue but it might be interesting to add the possibility to have some actors set as not interracting with "link token"

the problem gets worse with token attacher. if the cart and region are build with TA and the horse actor is added with Mass edit, then when the horse colides with the region :
-the region updates a movement
-Mass edit recieved movement from the horse and updates movement
-loop

and your horse cart and region hop off screen. 

i hope i am allowed to post this here. cheers all. FVTT_V12

**Comment by Aedif** [comment]
Should be fixed in: https://github.com/Aedif/multi-token-edit/releases/tag/1.75.0
