### ISSUE TITLE
[Bug] Cannot Open if Set to Deactivated Module Journal

### ISSUE THREAD

**Issue by Crowguard** [Aedif/multi-token-edit#45]
The Mass Edit window cannot be opened if it was set to use a journal from a deactivated/uninstalled/missing module. The journal I use is from a compendium module that was deactivated due to FTC for another issue, and it seems there is no way to change the journal without opening the window.

![Foundry_Virtual_Tabletop_vPGmxp3qRr](https://github.com/user-attachments/assets/a5fcf719-605a-4240-ac52-bf21af8de22e)

https://github.com/user-attachments/assets/45e6489f-f3e0-4c53-93aa-3da861e71e55

Foundry 12.331
Mass Edit 1.74.1

**Comment by Aedif** [comment]
Run this in a macro or console as a temporary fix:

`game.settings.set('multi-token-edit', 'workingPack', 'world.mass-edit-presets-main')`

**Comment by Aedif** [comment]
Should be fixed in: https://github.com/Aedif/multi-token-edit/releases/tag/1.75.0
