### ISSUE TITLE
[Bug] Placable Elevation

### ISSUE THREAD

**Issue by Crowguard** [Aedif/multi-token-edit#46]
Tiles (shown) & tokens (not shown) are not being placed at their saved elevation, they default back to 0.

https://github.com/user-attachments/assets/816dd16d-18fb-45e9-9ad1-ffc91a412e73

Lights are being placed at the inverse elevation.

https://github.com/user-attachments/assets/e4071cb8-29df-4e6f-b83d-5b5c18b521fa

Have not tested other entity types.

Foundry 12.331
Mass Edit 1.74.1

**Comment by Aedif** [comment]
Should be fixed in: https://github.com/Aedif/multi-token-edit/releases/tag/1.75.0
