### ISSUE TITLE
[Question] Is there a way I can create a macro to select all doors while on the wall layer?

### ISSUE THREAD

**Issue by EmoCthulhu** [Aedif/multi-token-edit#49]
I don't seem to see a listing for 'door' under search, just 'wall'. I used to do this with ripper93's Power Select Toolkit, but he killed it saying Mass Edit would do everything it did, but this is one thing I can't figure out how to do.

**Comment by Aedif** [comment]
With any wall selected press `Shift+F` and then set/select the field you want to search by:

https://github.com/user-attachments/assets/c1b682cd-1755-4ab8-964e-c54ca47d1ae4


If you want to use the module to create a macro:


https://github.com/user-attachments/assets/043f3981-c4ae-49b2-931c-5fd8e1c3b663

**Comment by EmoCthulhu** [comment]
Thanks so much for the help. I'm still working on the macro to do what I want, but I'll get it. Thanks again.
