### ISSUE TITLE
[Feature Request] Add ability to confugure ownership of selected tokens and map notes

### ISSUE THREAD

**Issue by Chryron** [Aedif/multi-token-edit#5]
The Multiple Document Selection module already allows editing the ownership of multiple actors and journal entries at once through the sidebar, but having the ability to select tokens and map notes on a scene, either manually or using mass-edit's search functionality and then configure their ownership at once would be a very useful feature to add! Not sure how easy this is to do but if possible adding this functionality in v9 would be incredible!

**Comment by Aedif** [comment]
Ran into this problem myself wanting to reveal notes on the map one at a time as players discovered them. Doing it through the side-bar was quite annoying....

I've got something working in Mass Edit which I used successfully but will need to go through testing it a bit more thoroughly before releasing it.

So this is just a heads up that the feature is on the way.

**Comment by Chryron** [comment]
That's the exact same use case I needed it for! Thought it might be useful to universally apply to everything that could be selected and have their permissions changed, so mentioned actors and tokens as well! But yeah the main reason I needed it was to selectively hide/reveal map notes on a city map as my players discovered them.

**Comment by Aedif** [comment]
Permission editing via Mass Edit forms is now possible as of release [1.16.0](![image](https://user-images.githubusercontent.com/7693704/192585241-e3e315cb-9325-44c0-91c6-9a228e8d1731.png)). Should work on both v9 and v10.
