### ISSUE TITLE
Feature Request: Setting to adjust alpha threshold for Pixel Perfect Hover 

### ISSUE THREAD

**Issue by Dumbhuman** [Aedif/multi-token-edit#50]
First off, thank you so much for the Pixel Perfect Hover feature!  It's something I can get a lot of use out of between modular tiles and overlapping token situations.

While experimenting with it, I noticed that anything below 80% alpha isn't selected, but a setting to change that threshold would be much appreciated.  In the video below where I show off how helpful it is for most scenarios with tokens, you can see that it's a little bit tricky for me to select the Big Blue Hand and impossible for me to select the top Gelatinous Cube while using Pixel Perfect Hover.  I'd love to be able to lower that alpha threshold and be able to select those two tokens more easily, but of course I can see plenty of use cases for keeping it higher, so ideally a setting would allow for the most flexibility. 

[MassEditPixelPerfectTransparency.webm](https://github.com/user-attachments/assets/18728cdf-d650-4a96-83dd-8c860706a9d6)

**Comment by Aedif** [comment]
https://github.com/Aedif/multi-token-edit/releases/tag/1.76.0

**Comment by Dumbhuman** [comment]
Just wanted to say thanks for adding this, because it's working great in my testing!
