### ISSUE TITLE
[Improvement] Ability to remove Pixel Perfect toggle from toolbar

### ISSUE THREAD

**Issue by TrofimSelbs** [Aedif/multi-token-edit#53]
Hey! Let me start by saying that I love this module. You have saved hours of my life. Thank you!

I am asking if possible, to add an option in settings to remove Pixel Perfect hover from toolbar. I don't use it and I try to have as little in my tools section as possible. Thank you in advance!

**Comment by Aedif** [comment]
https://github.com/Aedif/multi-token-edit/releases/tag/1.77.0
