### ISSUE TITLE
[Feature Request] Add compatibility with Multiple Document Selection and map notes

### ISSUE THREAD

**Issue by Chryron** [Aedif/multi-token-edit#6]
Mutiple Document Selection currently works with Mass Edit to change selected token and scene configuration settings, but adding the ability to change map note settings for journal entries selected with MDS would also be very helpful.

![image](https://user-images.githubusercontent.com/43299520/189527145-6f0df87f-d145-40c4-a27f-6c9d2e2c0841.png)

**Comment by Aedif** [comment]
So... as far as I can tell it is not possible to assign a Note configuration to a JournalEntry. As in you can't selected a JournalEntry, update the Entry Icon, and then have that be the icon for each subsequent note you drop on the map.

It is however possible to select JournalEntries using MDS and then have Mass Edit update all the existing Notes on the current Scene.

In fact it's even possible to update all the Notes corresponding to that Journal Entry on ALL scenes.

I'm not sure which would be preferable here...

**Comment by Chryron** [comment]
Having an option to select whether to update it on the current scene or all scenes would probably be best in my opinion. However having fine control over which scenes get updated map notes would probably be the ideal solution, but that might be too much work or might require additional U.I. elements to select scenes to apply changes to, so might not be worth it.

**Comment by Aedif** [comment]
Notes can now be edited via MDS JournalEntry selections as of release [1.12.0](https://github.com/Aedif/multi-token-edit/releases/tag/1.12.0)
