### ISSUE TITLE
Feature request: toggle status markers with mass edit

### ISSUE THREAD

**Issue by franckflo** [Aedif/multi-token-edit#8]
Currently there are not a lot of system-agnostic tools allowing enabling/disabling status markers, it would be a great addition for Mass Edit IMO. Allowing multiple changes in one pass would be great. Thanks !

**Comment by Aedif** [comment]
Hi, I'm not sure I'm following exactly that you wish to do. Apply status effects to multiple tokens at once? This can already be done using DFreds Convenient Effects

**Comment by franckflo** [comment]
I know, but DF convenients effects is not system agnostic, it requires DnD5e. It would be nice to a system-agnostic tool allowing to do that, no matter what status effects are available in the system.

**Comment by Aedif** [comment]
I don't think there is a system agnostic way of writing up code for this.

DnD5e uses the Foundry's inbuilt handling of effects, while a system such as PF2e completely overwrites it and does its own thing.

It would probably be relatively simple to write something and make it work for DnD5e and I'd assume the majority of all other systems out there, but there will be outliers that would need to be examined on case by case basis.

**Comment by franckflo** [comment]
I see, no biggie. Thanks for looking into it!

**Comment by Aedif** [comment]
Closing as this is already can be done using another module, using the same method as the one I considered for ME.

https://foundryvtt.com/packages/multistatus

Same limitaiton apply; if the game system significantly modifies how statuses work the module will fail.
