### ISSUE TITLE
Module no longer works in Foundry v9 despite being marked as compatible.

### ISSUE THREAD

**Issue by tnarv** [Aedif/multi-token-edit#9]
When trying to install the module on Foundry, you receive a warning:

![image](https://user-images.githubusercontent.com/75012229/198450610-393b1ec2-ae37-4fc2-bb78-8cad64269b18.png)

![image](https://user-images.githubusercontent.com/75012229/198451412-5c10eed5-4a8d-42b3-b526-eff4c2e9c082.png)

Using Forge's easy rollback system to do some further testing, looks like version 1.23.0 still loads and shows just fine into a Forge v9 foundry instance. Every version after that doesn't show up when configuring modules indicating incompatibility.

**Comment by Aedif** [comment]
Should be fixed now.

**Comment by Aedif** [comment]
Updated the manifest fields to v10 ones and didn't realise they were not backwards compatible.
